# Generated by Django 4.2.1 on 2023-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unanswered'), (2, 'Acssepted'), (3, 'Declained')], default=1, null=True),
        ),
    ]
